Updated the steam-wrapper script to a more modern format

diff --git a/steam-wrapper b/steam-wrapper
--- a/steam-wrapper
+++ b/steam-wrapper
@@ -6,7 +6,7 @@ set -o pipefail
 ##
 # Wrapper version
 ##
-VERSION=0.1.8
+version=0.1.8
 
 ##
 # steam-wrapper
@@ -16,7 +16,7 @@ VERSION=0.1.8
 ##
 # Check the environment path for the given binary, exit if it is not found
 ##
-checkForBinary() {
+function check_binary() {
 	if ! which "$1" > /dev/null 2>&1; then
 		printf "The '%s' binary is required for operation of this script.\n" "$1"
 		printf "Please install '%s' onto your system.\n" "$1"
@@ -29,9 +29,9 @@ checkForBinary() {
 ##
 function log_opening()
 {
-	if [[ $DEBUG -eq 1 ]]; then
-		echo -n "steam-wrapper[$VERSION]: Launched on " >> $LOG
-		echo "$(date +%Y-%m-%d) at $(date +%R) [$(date +%r)]" >> $LOG
+	if [[ "${debug}" -eq 1 ]]; then
+		echo -n "steam-wrapper[${version}]: Launched on " >> "${log}"
+		echo "$(date +%Y-%m-%d) at $(date +%R) [$(date +%r)]" >> "$log"
 	fi
 }
 
@@ -40,16 +40,16 @@ function log_opening()
 ##
 function log_config_location()
 {
-	if [[ $DEBUG -eq 1 ]]; then
-		if [[ $CONF_LOCATION != "" ]]; then
-			echo -n "steam-wrapper[$VERSION]: " >> $LOG
-			echo -n "Configuration file " >> $LOG
-			echo "found at: $CONF_LOCATION" >> $LOG
+	if [[ "${debug}" -eq 1 ]]; then
+		if [[ $conf_location != "" ]]; then
+			echo -n "steam-wrapper[${version}]: " >> "${log}"
+			echo -n "Configuration file " >> "${log}"
+			echo "found at: $conf_location" >> "${log}"
 		else
-			echo -n "steam-wrapper[$VERSION]: " >> $LOG
-			echo -n "No configuration " >> $LOG
-			echo "file found" >> $LOG
-			echo "Using preset defaults." >> $LOG
+			echo -n "steam-wrapper[${version}]: " >> "${log}"
+			echo -n "No configuration " >> "${log}"
+			echo "file found" >> "${log}"
+			echo "Using preset defaults." >> "${log}"
 		fi
 	fi
 }
@@ -60,13 +60,13 @@ function log_config_location()
 function steam_folder_exists()
 {
 	if [[ -d $HOME/.steam ]]; then
-		echo -n "steam-wrapper[$VERSION]: Steam folder " >> $LOG
-		echo "exists, can continue" >> $LOG
+		echo -n "steam-wrapper[${version}]: Steam folder " >> "${log}"
+		echo "exists, can continue" >> "${log}"
 		return 0
 	else
-		echo -n "steam-wrapper[$VERSION]: Steam folder " >> $LOG
-		echo "doesn't exist, launch Steam first" >> $LOG
-		echo -n "steam-wrapper[$VERSION]: Steam folder "
+		echo -n "steam-wrapper[${version}]: Steam folder " >> "${log}"
+		echo "doesn't exist, launch Steam first" >> "${log}"
+		echo -n "steam-wrapper[${version}]: Steam folder "
 		echo "doesn't exist, launch Steam first"
 		return 1
 	fi
@@ -80,12 +80,12 @@ function steam_folder_exists()
 ##
 function remove_stale_files()
 {
-	if [[ $DEBUG -eq 1 ]]; then
-		echo -n "steam-wrapper[$VERSION]: Attempting removal " >> $LOG
-		echo "of stale libraries..." >> $LOG
+	if [[ "${debug}" -eq 1 ]]; then
+		echo -n "steam-wrapper[${version}]: Attempting removal " >> "${log}"
+		echo "of stale libraries..." >> "${log}"
 		find $HOME/.steam \( -name "libgcc_s.so*" -o \
 			-name "libstdc++.so*" -o -name "libxcb.so*" \) \
-			-delete -print >> $LOG
+			-delete -print >> "${log}"
 	else
 		find $HOME/.steam \( -name "libgcc_s.so*" -o \
 			-name "libstdc++.so*" -o -name "libxcb.so*" \) -delete
@@ -97,17 +97,17 @@ function remove_stale_files()
 ##
 function link_lib32_flash()
 {
-	local ARCH=$(uname -m)
-	if [[ $ARCH = "x86_64" ]]; then
-		[[ $DEBUG -eq 1 ]] && {
-			echo -n "steam-wrapper[$VERSION]: " >> $LOG
-			echo -n "Attempt linking of lib32 " >> $LOG
-			echo "libflashplayer.so" >> $LOG
+	local arch=$(uname -m)
+	if [[ $arch = "x86_64" ]]; then
+		[[ "${debug}" -eq 1 ]] && {
+			echo -n "steam-wrapper[${version}]: " >> "${log}"
+			echo -n "Attempt linking of lib32 " >> "${log}"
+			echo "libflashplayer.so" >> "${log}"
 		}
 		if [[ -f $HOME/.steam/bin/plugins/libflashplayer.so ]]; then
-			if [[ $DEBUG -eq 1 ]]; then
-				echo -n "steam-wrapper[$VERSION]: " >> $LOG
-				echo "Flashplayer is already linked." >> $LOG
+			if [[ "${debug}" -eq 1 ]]; then
+				echo -n "steam-wrapper[${version}]: " >> "${log}"
+				echo "Flashplayer is already linked." >> "${log}"
 			fi
 		elif [[ -f /usr/lib32/mozilla/plugins/libflashplayer.so ]]; then
 			mkdir -p $HOME/.steam/bin/plugins
@@ -117,18 +117,18 @@ function link_lib32_flash()
 			##
 			ln -sf /usr/lib32/mozilla/plugins/libflashplayer.so \
 				$HOME/.steam/bin/plugins/libflashplayer.so
-			if [[ $DEBUG -eq 1 ]]; then
-				echo -n "steam-wrapper[$VERSION]: " >> $LOG
-				echo "Linked libflashplayer.so" >> $LOG
+			if [[ "${debug}" -eq 1 ]]; then
+				echo -n "steam-wrapper[${version}]: " >> "${log}"
+				echo "Linked libflashplayer.so" >> "${log}"
 			fi
 		else
-			if [[ $DEBUG -eq 1 ]]; then
-				echo -n "steam-wrapper[$VERSION]: " >> $LOG
-				echo "Cannot find libflashplayer.so" >> $LOG
+			if [[ "${debug}" -eq 1 ]]; then
+				echo -n "steam-wrapper[${version}]: " >> "${log}"
+				echo "Cannot find libflashplayer.so" >> "${log}"
 			fi
 		fi
 	fi
-	unset ARCH
+	unset arch
 }
 
 ##
@@ -136,16 +136,16 @@ function link_lib32_flash()
 ##
 function log_wrapper_usage()
 {
-	if [[ $DEBUG -eq 1 ]]; then
-		echo "steam-wrapper[$VERSION]: Done." >> $LOG
-		echo -n "steam-wrapper[$VERSION]: Launching steam with" >> $LOG
-		echo " environment:" >> $LOG
-		echo -n "steam-wrapper[$VERSION]:     STEAM_RUNTIME =" >> $LOG
-		echo " ${USE_RUNTIME}" >> $LOG
-		echo -n "steam-wrapper[$VERSION]:     " >> $LOG
-		echo -n "STEAM_FRAME_FORCE_CLOSE = " >> $LOG
-		echo "${CLOSE_TO_TRAY}" >> $LOG
-		echo >> $LOG
+	if [[ "${debug}" -eq 1 ]]; then
+		echo "steam-wrapper[${version}]: Done." >> "${log}"
+		echo -n "steam-wrapper[${version}]: Launching steam with" >> "${log}"
+		echo " environment:" >> "${log}"
+		echo -n "steam-wrapper[${version}]:     STEAM_RUNTIME =" >> "${log}"
+		echo " ${use_runtime}" >> "${log}"
+		echo -n "steam-wrapper[${version}]:     " >> "${log}"
+		echo -n "STEAM_FRAME_FORCE_CLOSE = " >> "${log}"
+		echo "${close_to_tray}" >> "${log}"
+		echo >> "${log}"
 	fi
 }
 
@@ -155,18 +155,18 @@ function log_wrapper_usage()
 ##
 function find_conf()
 {
-	local CONF_LOCATION=""
+	local conf_location=""
 	if [[ -f $HOME/.steam-wrapper/steam-wrapper.conf ]]; then
-		CONF_LOCATION="$HOME/.steam-wrapper/steam-wrapper.conf"
+		conf_location="$HOME/.steam-wrapper/steam-wrapper.conf"
 	elif [[ -f $HOME/.steam-wrapper.conf ]]; then
-		CONF_LOCATION="$HOME/.steam-wrapper.conf"
+		conf_location="$HOME/.steam-wrapper.conf"
 	elif [[ -f /etc/steam-wrapper/steam-wrapper.conf ]]; then
-		CONF_LOCATION="/etc/steam-wrapper/steam-wrapper.conf"
+		conf_location="/etc/steam-wrapper/steam-wrapper.conf"
 	elif [[ -f /etc/steam-wrapper.conf ]]; then
-		CONF_LOCATION="/etc/steam-wrapper.conf"
+		conf_location="/etc/steam-wrapper.conf"
 	fi
-	echo $CONF_LOCATION
-	unset CONF_LOCATION
+	echo "${conf_location}"
+	unset conf_location
 }
 
 function main()
@@ -176,31 +176,31 @@ function main()
 	checkForBinary find
 	checkForBinary printf
 
-	local CONF_LOCATION
-	local DEBUG
-	local USE_RUNTIME
-	local CLOSE_TO_TRAY
-	local LOGDIR
-	local LOG
+	local conf_location
+	local debug
+	local use_runtime
+	local close_to_tray
+	local logdir
+	local log
 
-	CONF_LOCATION=$(find_conf) || return 1
+	conf_location=$(find_conf) || return 1
 
 	##
 	# If a configuration file was present, source it for use, otherwise
 	# we will use pre-defined varialbes which are arguably sensible by
 	# default.
 	##
-	if [[ $CONF_LOCATION != "" ]]; then
-		source $CONF_LOCATION
+	if [[ "${conf_location}" != "" ]]; then
+		source "${conf_location}"
 	else
-		DEBUG=1
-		USE_RUNTIME=1
-		CLOSE_TO_TRAY=1
-		LOGDIR="$HOME/.steam-wrapper/"
+		debug=1
+		use_runtime=1
+		close_to_tray=1
+		logdir="$HOME/.steam-wrapper/"
 	fi
 
-	LOG="$LOGDIR/steam-wrapper.log"
-	mkdir -p $LOGDIR
+	log="$logdir/steam-wrapper.log"
+	mkdir -p "${logdir}"
 
 	log_opening || return 1
 	log_config_location || return 1
@@ -212,14 +212,14 @@ function main()
 	##
 	# Clean up some of the unused vars
 	##
-	unset DEBUG LOGDIR LOG CONF_LOCATION
+	unset debug logdir log conf_location
 
 	##
 	# Run steam using the wrapper
 	##
 	exec env \
-		STEAM_RUNTIME="${USE_RUNTIME}" \
-		STEAM_FRAME_FORCE_CLOSE="${CLOSE_TO_TRAY}" \
+		STEAM_RUNTIME="${use_runtime}" \
+		STEAM_FRAME_FORCE_CLOSE="${close_to_tray}" \
 		steam "$@"
 	return 0
 }
